### ISSUE TITLE
关于yolov4或yolov4-tiny在mnn中的推理情况

### ISSUE THREAD

**Issue by lq0104** [dog-qiuqiu/MobileNet-Yolo#19]
你好，想了解一下yolov4或者yolov4-tiny目前能在mnn推理框架中使用吗，有没有推理时间的测试数据啊

**Comment by dog-qiuqiu** [comment]
暂时没有，但是我测的ncnn是早期的数据，后来ncnn优化了arm82，速度已经和mnn不相上下了

**Comment by lq0104** [comment]
哦哦，那最新的ncnn速度可不可以再更新一下哈，还有TNN你那边试过吗，可以成功跑yolov4不

**Comment by dog-qiuqiu** [comment]
TNN是可以跑通的官方已经支持，不过得基于我的darknet2caffe把模型转换为caffemodel才能移植，或者直接转为ncnn的模型格式再用TNN调用，还有关于YOLOV4的问题，我觉得在arm跑官方yolov4是毫无意义的，本质计算量参数量太大了，耗时都在s级，我测试过基于contex-A76 ncnn跑yolov4 在10s左右...

**Comment by lq0104** [comment]
10s...哈，了解了，谢谢大佬解答了
